import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {Toaster} from 'react-hot-toast'

import './globals.css'
import '@fontsource/roboto/300.css'
import '@fontsource/roboto/400.css'
import '@fontsource/roboto/500.css'
import '@fontsource/roboto/700.css'

import AuthContext from './context/AuthContext'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Nextjs Admin Console',
  description: 'Generated by create next app'
}

export default async function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
          <Toaster />
          {children}
        </AuthContext>
      </body>
    </html>
  )
}
